# Generated by Django 4.2 on 2023-06-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('customer_and_user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalReportList',
            fields=[
                ('analytical_report_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
            options={
                'verbose_name_plural': '2. AnalyticalReportList',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('user_activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=50)),
                ('activity_time', models.DateTimeField()),
                ('activity_type', models.CharField(max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. UserActivityLog',
            },
        ),
        migrations.CreateModel(
            name='SmsDeliveryLog',
            fields=[
                ('sms_delivery_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_type', models.CharField(max_length=20)),
                ('event_or_action', models.CharField(max_length=10)),
                ('sms_body', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
            options={
                'verbose_name_plural': '6. SmsDeliveryLog',
            },
        ),
        migrations.CreateModel(
            name='ReportDeliverySchedule',
            fields=[
                ('report_delivery_scheudle_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_frequency', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('last_delivered_date', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('analytical_report_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_activity_log.analyticalreportlist')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. ReportDeliverySchedule',
            },
        ),
        migrations.CreateModel(
            name='ReportDeliveryLog',
            fields=[
                ('report_delivery_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('error_message', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('report_delivery_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_activity_log.reportdeliveryschedule')),
            ],
            options={
                'verbose_name_plural': '4. ReportDeliveryLog',
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('email_delivery_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_type', models.CharField(max_length=20)),
                ('delivery_date', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
            options={
                'verbose_name_plural': '5. EmailDeliveryLog',
            },
        ),
    ]
