# Generated by Django 4.2 on 2023-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_created_at_alter_contract_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractattachment',
            name='file_path',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
