# Generated by Django 4.2 on 2023-06-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_and_user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicyRule',
            fields=[
                ('password_policy_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('possword_policy_rule', models.CharField(max_length=40)),
                ('answer_type', models.CharField(max_length=10)),
                ('possible_answers', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '1. PasswordPolicyRule',
            },
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('password_policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('password_policy_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_policy.passwordpolicyrule')),
            ],
            options={
                'verbose_name_plural': '2. PasswordPolicy',
            },
        ),
    ]
