# Generated by Django 4.2 on 2023-06-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('customer_and_user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContractStatus',
            fields=[
                ('uploaded_contract_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_contract_state', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '3. UploadedContractStatus',
            },
        ),
        migrations.CreateModel(
            name='UploadContract',
            fields=[
                ('uploaded_contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_date', models.DateTimeField()),
                ('contract_source_type', models.CharField(max_length=20)),
                ('contract_source_address', models.CharField(max_length=50)),
                ('contract_destination_address', models.CharField(max_length=50)),
                ('contract_upload_status', models.CharField(max_length=20)),
                ('contract_upload_filure_reasons', models.CharField(max_length=20)),
                ('metadata_source_type', models.CharField(max_length=20)),
                ('metadata_source_address', models.CharField(max_length=50)),
                ('metadata_destination_address', models.CharField(max_length=50)),
                ('metadata_upload_status', models.CharField(max_length=20)),
                ('metadata_upload_filure_reasons', models.CharField(max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('uploaded_contract_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contractstatus')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. UploadContract',
            },
        ),
        migrations.CreateModel(
            name='RenewContract',
            fields=[
                ('renew_contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('renewed_data', models.DateTimeField()),
                ('remarks', models.CharField(max_length=20)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('renewed_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. RenewContract',
            },
        ),
    ]
