# Generated by Django 4.2 on 2023-06-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('customer_and_user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemList',
            fields=[
                ('action_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=200)),
                ('action_description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('eta', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('current_status', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('assigned_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
            options={
                'verbose_name_plural': '1.  action_item_list ',
            },
        ),
    ]
