# Generated by Django 4.2 on 2023-06-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_and_user_management', '0001_initial'),
        ('contract', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata_key', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
                ('created_by_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractReviewer',
            fields=[
                ('contract_reviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_status', models.IntegerField()),
                ('review_order', models.IntegerField(unique=True)),
                ('internal_or_external', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractMetadata',
            fields=[
                ('contract_metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata_value', models.CharField(max_length=255)),
                ('additional_meta_tag_id', models.CharField(max_length=255)),
                ('added_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('metadata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_review_approval.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='ContractApprover',
            fields=[
                ('contract_approver_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_order', models.IntegerField()),
                ('approve_status', models.IntegerField()),
                ('internal_or_external', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractActivityLog',
            fields=[
                ('contract_activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('activity_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contractreviewer',
            constraint=models.UniqueConstraint(fields=('contract_id', 'review_order'), name='unique_contract_review_order_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='contractapprover',
            constraint=models.UniqueConstraint(fields=('contract_id', 'review_order'), name='unique_contract_review_order_approver'),
        ),
    ]
