# Generated by Django 4.2 on 2023-06-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('message_templates', '0001_initial'),
        ('customer_and_user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsRegion',
            fields=[
                ('aws_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('aws_region', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '1. AwsRegion',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('to', models.TextField()),
                ('cc', models.TextField()),
                ('bcc', models.TextField()),
                ('reply_to', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.CharField(max_length=50)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('notification_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_templates.notificationevent')),
            ],
            options={
                'verbose_name_plural': '3. Email',
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('email_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muti_region_hosting.email')),
            ],
            options={
                'verbose_name_plural': '4. EmailAttachment',
            },
        ),
        migrations.CreateModel(
            name='CountryAwsRegion',
            fields=[
                ('country_aws_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muti_region_hosting.awsregion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.countrycontract')),
            ],
            options={
                'verbose_name_plural': '2. CountryAwsRegion',
            },
        ),
    ]
