# Generated by Django 4.2 on 2023-06-30 11:25

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('contact_phone_number', models.CharField(max_length=14, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('password_reset_token', models.CharField(max_length=100, null=True)),
                ('password_reset_token_sent_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('currency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.currency')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_url', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('contact_number', models.CharField(max_length=14)),
                ('gst_tax_number', models.CharField(max_length=10)),
                ('company_logo_url', models.CharField(max_length=100)),
                ('company_image', models.ImageField(upload_to='company_images/')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=14)),
                ('licence_type', models.CharField(max_length=8)),
                ('licence_start_date', models.DateField()),
                ('licence_end_date', models.DateField()),
                ('licence_user_quantity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('is_social_login_enabled', models.BooleanField(default=False)),
                ('unique_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('org_admin_email', models.EmailField(max_length=50)),
                ('org_admin_full_name', models.CharField(max_length=100)),
                ('org_admin_contact_number', models.CharField(max_length=14)),
                ('contract_manager_email', models.EmailField(max_length=50)),
                ('contract_manager_full_name', models.CharField(max_length=100)),
                ('contract_manager_contact_number', models.CharField(max_length=14)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.country')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('role_type', models.CharField(choices=[('ContractManagement', 'Contract Management'), ('OperationalManagement', 'Operational Management')], max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_group_lead', models.BooleanField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.role')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('group_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_group_lead', models.BooleanField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.group')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_format_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.dateformat'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, to='customer_and_user_management.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(null=True, through='customer_and_user_management.UserRole', to='customer_and_user_management.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer_and_user_permissions', to='customer_and_user_management.permission', verbose_name='user permissions'),
        ),
    ]
