# Generated by Django 4.2 on 2023-06-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_and_user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('counterparty_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_web', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('company_contact_number', models.CharField(max_length=14)),
                ('city', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.country')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyContact',
            fields=[
                ('counterparty_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparty.counterparty')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCounterpartyContact',
            fields=[
                ('customer_counterparty_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparty.counterpartycontact')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
        ),
    ]
