# Generated by Django 4.2 on 2023-06-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_and_user_management', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('notification_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_event', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
            options={
                'verbose_name_plural': '1. NotificationEvent',
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('sms_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_text', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('notication_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_templates.notificationevent')),
            ],
            options={
                'verbose_name_plural': '3. SmsTemplate',
            },
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('notification_scheudle_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('schedule_date', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPerod',
            fields=[
                ('notification_period_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_type', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('number_of_reminders', models.IntegerField()),
                ('gap_between_reminders', models.IntegerField()),
                ('days_in_advance', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('notification_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_templates.notificationevent')),
            ],
            options={
                'verbose_name_plural': '2. NotificationPerod',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('email_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_text', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer')),
                ('notication_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_templates.notificationevent')),
            ],
            options={
                'verbose_name_plural': '2. EmailTemplate',
            },
        ),
    ]
