# Generated by Django 4.2 on 2023-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbAuditLog',
            fields=[
                ('db_audit_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_description', models.CharField(max_length=200)),
                ('event_date_time', models.DateTimeField()),
                ('event_type', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=20)),
                ('impacted_row_pk_id', models.IntegerField()),
                ('impacted_column_name', models.CharField(max_length=20)),
                ('old_value', models.CharField(max_length=20)),
                ('new_value', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '1. DbAuditLog',
            },
        ),
    ]
