# Generated by Django 4.2 on 2023-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_code', models.CharField(max_length=30)),
                ('currency', models.CharField(default='USD', max_length=30)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '2. Currency',
            },
        ),
        migrations.CreateModel(
            name='DateFormat',
            fields=[
                ('date_format_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_format', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '3. DateFormat',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '1. Language',
            },
        ),
    ]
